mixed-port: 1081
allow-lan: true
mode: rule
log-level: info
proxies:
- name: 🇯🇵 免费-日本1-Ver.7
  server: ovhfzym-g04.jp01-nn-vm0.entry.fr0528.art
  port: 21584
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: true
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本2-Ver.8
  server: a0hw4y1-g04.jp02-e3-vm0.entry.fr0528.art
  port: 11776
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本3-Ver.7
  server: i0oz4tc-g04.jp03-j7-vm0.entry.fr0528.art
  port: 21584
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: true
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本4-Ver.8
  server: aoozvym-g04.jp04-1d-vm0.entry.fr0528.art
  port: 447
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本5-Ver.9
  server: iohzzuy-g04.jp05-h6-vm0.entry.fr0528.art
  port: 46485
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本6-Ver.8
  server: i1ow4tm-g04.jp06-jz-vm0.entry.fr0528.art
  port: 28786
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: true
  skip-cert-verify: false
  udp: true
- name: 🇯🇵 免费-日本7-Ver.2
  server: hvhzvyy-g04.jp07-sh-vm0.entry.fr0528.art
  port: 28786
  type: vmess
  uuid: f38fe9d0-3ab5-32cc-9082-b9cb5ba99443
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
proxy-groups:
- name: LB
  type: load-balance
  url: https://www.gstatic.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
  - 🇯🇵 免费-日本1-Ver.7
  - 🇯🇵 免费-日本2-Ver.8
  - 🇯🇵 免费-日本3-Ver.7
  - 🇯🇵 免费-日本4-Ver.8
  - 🇯🇵 免费-日本5-Ver.9
  - 🇯🇵 免费-日本6-Ver.8
  - 🇯🇵 免费-日本7-Ver.2
rules:
- MATCH,LB
